server:
  port: 8556
mybatis:
  type-aliases-package: com.aaa.pojo
  mapper-locations: classpath:com/aaa/mapper/**/*.xml
  configuration:
    auto-mapping-behavior: full
    use-column-label: true
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用 负载均衡
    fetch-registry: true
    service-url:
      #      defaultZone:  http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
      defaultZone:  http://eureka7001.com:7001/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/f4?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456
  thymeleaf:
    cache: false
    suffix: .html
  application:
    name: xdf4-provider-personnel
  jackson:
    date-format: yyyy-MM-dd
    timezone: GMT+8
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    com:
      aaa:
        mapper: debug