server:
  port: 8001

spring:
  application:
    name: xdf4-provider-conference
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/f4?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456
  thymeleaf:
    cache: false
    suffix: .html
  jackson:
    # 如果使用字符串星表示用这行格式
    date-format: yyyy-MM-dd HH:mm:ss
    # 设置为东八区时间
    timezone: GMT+8
    # 想要值为2016-01-01
    serialization:
      write-dates-as-timestamps: false

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.aaa.springcloud.pojo
  configuration:
    auto-mapping-behavior: full # \u8BBE\u7F6E\u5168\u81EA\u52A8\u6620\u5C04
    use-column-label: true # \u8BBE\u7F6E\u522B\u540D\u53EF\u4EE5\u505A\u5217\u540D

# 显示SQL语句
logging:
  level:
    com:
      aaa:
        springcloud:
          mapper: debug

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用 负载均衡
    fetch-registry: true
    service-url:
      #      defaultZone:  http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
      defaultZone:  http://eureka7001.com:7001/eureka/

#设置feign客户端超时时间
ribbon:
  # 建立连接所用时间
  ReadTimeout: 5000
  # 建立连接后读取可用资源所用的时间
  ConnectTimeout: 5000

